name: CustomPortals
main: com.ghomerr.customportals.CustomPortals
version: 1.1.3 [1.6.2-R0.1]
author: Ghomerr
description: Make your own fancy portals.

commands:
    customportals:
        description: Make your own fancy portals.
        aliases: [cp, custportals, customportal, cportal]
