name: CustomPortals
main: com.ghomerr.customportals.CustomPortals
version: 1.1.2 [1.5.1-R0.2]
author: Ghomerr
description: Make your own fancy portals.

commands:
    customportals:
        description: Make your own fancy portals.
        aliases: [cp, custportals, customportal, cportal]
