name: CustomPortals
main: com.ghomerr.customportals.CustomPortals
version: 1.1.1 [1.4.7-R1.0]
author: Ghomerr
description: Make your own fancy portals.

commands:
    customportals:
        description: Make your own fancy portals.
        aliases: [cp, custportals, customportal, cportal]
